apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: hub.docker.com/yaleits/ecr-api
    buildpacks:
      builder: paketobuildpacks/builder:tiny
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: ecrapi
      chartPath: k8s/api
      artifactOverrides:
        image: hub.docker.com/yaleits/ecr-api
      setFiles:
        apiconfig: config/config.json
      valuesFiles:
        - k8s/values.yaml
