replicaCount: 1

# image:
#   repository: hub.docker.com/yaleits/ecr-api

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  rules:
    - paths: ['/v1/ecr']

probePath: '/v1/ecr/ping'
